### ISSUE TITLE
Does not compile on MacOS/32bit platforms

### ISSUE THREAD

**Issue by curddd** [nrootconauto/3Days#11]
can you make wasm thing?

**Comment by nrootconauto** [comment]
### Ayo Dog,WASM will not happen on 3days but...
I am working on a secret project called _AIWNIOS_ which runs on ARM,but im working on other stuff now,but in a week I will resume course on AIWNIOS. I have gutted the TempleOS compiler code generator and replaced it with a C version,so porting TempleOS to wasm seems not that far out.

3Days is deeply rooted in X86_64 assembly. As for the septic sauce not compiling. IU

**Comment by nrootconauto** [comment]
Sorry for closing the thing,I thought pressing the "close with comment" button would give me a menu to *not* close the thing

**Comment by nrootconauto** [comment]
Ditto

**Comment by curddd** [comment]
okay, why dont someone port templeos back to 32bit?

or, could i get it compiled on ... macos?

do i need to emulate a x64 architecture and install debian for this to go? does that work

whats the irc server xD

**Comment by nrootconauto** [comment]
I have no MacOS machines. Ill install a hackintosh

**Comment by contextswap** [comment]
Unfortunately 32bit architectures are not supported due to TempleOS' extensive usage of 64 bit intructions and values make 32bit support infeasible.
The same also applies to WASM as it is technically a 32bit system.

As for MacOS support, it currently is infeasible due to poopalloc.c reading <procfs dir>/self/maps directly as per UNIX philosophy and MacOS not providing procfs.

Notes in case this issue is revisited:
https://github.com/alexchandel/procfs (procfs for macos)

**Comment by contextswap** [comment]
Closed as nofix after considering implementation and maintenance effort of MacOS support.
